### PR TITLE
Feature/user api skeleton

### PR DESCRIPTION
**Pull request by ShashiSrinath**
created

*Entities*
- AppUser
- Client
- Supplier

*repositiries*
- AppUserRepository
- ClientRepository
- SupplierRepository

UserController
UserService

### CODE REVIEW

**Comment by shevanthiranjafernando** [comment]
reviwe

**Comment by shevanthiranjafernando** [comment]
Review

**Comment by shevanthiranjafernando** [comment]
Review

**Review by ShashiSrinath — COMMENTED** [review]
self merging

**Review by shevanthiranjafernando — APPROVED** [review]
Review

**Pull request merged**
